### ISSUE TITLE
Compile errors with Raspberry pi 32 bit

### ISSUE THREAD

**Issue by ScallyBag** [mhib/combusken#4]
Hi,

Your engine has always compiled fine on my Raspberry Pi until recently,
I can’t get past these messages:

# github.com/mhib/combusken/engine
../gows/src/github.com/mhib/combusken/engine/search.go:222:56: constant 4294967295 overflows int
../gows/src/github.com/mhib/combusken/engine/search.go:648:146: timeSinceStart.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
../gows/src/github.com/mhib/combusken/engine/search.go:759:132: timeSinceStart.Milliseconds undefined (type time.Duration has no field or method Milliseconds)
Makefile:7: recipe for target 'combusken' failed
make: *** [combusken] Error 2

Thanks,

Alan Cooper aka Scally for Picochess.

**Comment by mhib** [comment]
Hi Alan,

Thank you for reporting this problem.

The int overflow issue should be fixed on the current master(I've tried compiling and running it on 32-bit Linux VM and it seems to work fine).

As for `Milliseconds` error, this method was added pretty recently in Go version 1.13. Please make sure that 1.13 or a newer version of Go is used for building Combusken.

Thanks,
Marcin

**Comment by ScallyBag** [comment]
Hi Marcin,

Thanks for your reply and fix. 
Installing go 1.13 is not so easy on a Raspberry Pi. I had managed to get go 1.10 on my RPi 3b+ (default is go 1.7) and the latest RPi 4b has go 1.11. I’m looking into it ...

Thanks,

Al.

**Comment by ScallyBag** [comment]
Hi Marcin,

I’ve managed to install go 1.13.11 and Combusken now installs and runs fine.

Thanks very much,

Al.

**Comment by mhib** [comment]
Hi Alan,

Thank you for your contribution.

Best Rargards,
Marcin
