### ISSUE TITLE
Ponder support?

### ISSUE THREAD

**Issue by CMCanavessi** [mhib/combusken#5]
Is there any plans to support ponder? I see there are some entries in the code about it, but seems disabled so far.

**Comment by mhib** [comment]
Hi, Carlos!

Combusken's development is currently on hold.

The ponder support was never a priority as it is rarely useful for analysis, and most of the chess engine tournaments/rating lists do not use it.

I do not rule out adding support for ponder, but not in the near future.

BR,
Marcin

**Comment by mhib** [comment]
Resolved in master with https://github.com/mhib/combusken/commit/529ba66ef84e70089516297415599ac79510a5b6.
Ponder will be available in the next release.
