### ISSUE TITLE
now v1.9.9 dev .. is v2.0 coming ?

### ISSUE THREAD

**Issue by tissatussa** [mhib/combusken#6]
i see your latest version is v1.4.0 from late oktober 2020 .. but when compiling your master code i get v1.9.9-dev .. it runs fine in CuteChess and SCID though. I think in the meantime you developed a lot, now having v1.9.9 ! 

are you still working on this engine ?  Is v2.0 coming soon ?

**Comment by mhib** [comment]
Hi!

Thank you for your interest!
Yes, I've started working on Combusken again.
Combusken v2.0 will be released, but I cannot provide any ETA as for now.
