### ISSUE TITLE
Cannot load

### ISSUE THREAD

**Issue by SzotsGabor** [mhib/combusken#8]
Hi Marcin,

I have successfully installed the newest Combusken under the Fritz GUI. However, I cannot install it under the Shredder GUI, it tells me "this is not a UCI engine".
I suspect this may be related to slow loading. I noticed that when I start the engine from the command line it leaves a lot of lines empty before it displays its name. I don't know why but maybe that is the reason why it cannaot be installed under Shredder.

**Comment by mhib** [comment]
Hi Gabor!

Thank you for reporting this!
I think I have resolved the issue; please try a new binary from https://github.com/mhib/combusken/releases/tag/v2.0.0

BR,
Marcin

**Comment by SzotsGabor** [comment]
Success! Thank you for the quick fix!
